# Generated by Django 4.2.5 on 2023-09-26 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cartorderitems_invoice_no_alter_vendor_user_wishlist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='order_dates',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='cartorderitems',
            old_name='items',
            new_name='item',
        ),
    ]
