# Generated by Django 4.2.5 on 2023-09-26 10:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_product_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
