# Generated by Django 4.2.5 on 2023-09-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='days_return',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vendor',
            name='warranty_period',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
