# Generated by Django 4.2.5 on 2023-09-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_vendor_days_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='days_return',
            field=models.CharField(default='No return', max_length=100),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='warranty_period',
            field=models.CharField(default='No warranty', max_length=100),
        ),
    ]
